# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_dir": "00_nsfg.ipynb",
         "dat_file": "00_nsfg.ipynb",
         "dct_file": "00_nsfg.ipynb",
         "type_sub": "00_nsfg.ipynb",
         "get_dct_dataframe": "00_nsfg.ipynb",
         "get_dat_dataframe": "00_nsfg.ipynb",
         "display_all": "00_nsfg.ipynb",
         "columns_of_interest": "00_nsfg.ipynb",
         "cleanup": "00_nsfg.ipynb",
         "clean_file_path": "00_nsfg.ipynb",
         "effect_size": "01_basic_stats.ipynb",
         "get_discrete_pmf": "01_basic_stats.ipynb",
         "central_moment": "01_basic_stats.ipynb",
         "moment": "01_basic_stats.ipynb",
         "PearsonsMedianSkewness": "01_basic_stats.ipynb",
         "plot_hist_with_kde": "01_basic_stats.ipynb",
         "get_mean_test_statistic": "02_hypothesis_testing.ipynb",
         "get_boot_test_statistics": "02_hypothesis_testing.ipynb",
         "get_p_value": "02_hypothesis_testing.ipynb",
         "plot_hist_with_kde_for_hypothesis_test": "02_hypothesis_testing.ipynb",
         "get_chi2_test_statistic": "02_hypothesis_testing.ipynb",
         "get_spearmanr_test_statistic": "02_hypothesis_testing.ipynb",
         "regression_coeffs_with_covar": "03_linear_least_squares.ipynb",
         "bootstrap_regression": "03_linear_least_squares.ipynb",
         "estimate_hazard_fun": "04_hazard_function.ipynb"}

modules = ["nsfg.py",
           "basic_stats.py",
           "hypothesis_testing.py",
           "linear_least_squares.py",
           "hazard_function.py"]

doc_url = "https://eschmidt42.github.io/thinkstats/"

git_url = "https://github.com/eschmidt42/thinkstats/tree/master/"

def custom_doc_links(name): return None
